CREATE USER LOGGING IDENTIFIED BY log4net;
GRANT ALTER SESSION TO LOGGING;
GRANT CREATE SESSION TO LOGGING;
ALTER USER LOGGING QUOTA UNLIMITED ON users;
GRANT UNLIMITED TABLESPACE TO LOGGING;

CREATE TABLE LOGGING.APPLICATION_LOG (
     SOURCE VARCHAR2(50 CHAR),
     UTC_DATE TIMESTAMP (6),
     THREAD VARCHAR2(255 CHAR),
     HOST VARCHAR2(255 CHAR),
     PROCESS VARCHAR2(255 CHAR),
     LOG_LEVEL VARCHAR2(50 CHAR),
     LOGGER VARCHAR2(255 CHAR),
     MESSAGE VARCHAR2(4000 CHAR),
     EXCEPTION CLOB);